bd_pass="nhm5QjITYfBRi51punlNCMnOBAmXXBvi"
TOKEN="6901425028:AAHZWuoptTLPLKyS-H42XSeeyX3SYuUqNQg"
DATABASE_URL = f"postgresql+asyncpg://dyvawvhc:{bd_pass}@trumpet.db.elephantsql.com/dyvawvhc"
# DATABASE_URL = f"postgresql+asyncpg://nusiykxb:{config.bd_pass}@lucky.db.elephantsql.com/nusiykxb"
api_key=""